"""delete_active

Revision ID: 559934568645
Revises: 73c904b84d9c
Create Date: 2023-01-22 14:25:30.910140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559934568645'
down_revision = '73c904b84d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
