"""Initial migration.

Revision ID: 73c904b84d9c
Revises: 
Create Date: 2023-01-19 13:53:55.455423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c904b84d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.BLOB(), nullable=False))

    # ### end Alembic commands ###
